name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: lukaszkostka/debian_gcc:${{ matrix.distro }}
      env:
        VERSION: ${{ matrix.version }}
        DH_VERBOSE: 0
    strategy:
      matrix:
        version:
          - 8.2.0
          - 8.3.0
        distro:
          - stretch
          - buster
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: src
          key: gcc-source-${{ matrix.version }}

      - name: Build package
        run: make deb
