name: Build

on:
  push:
    paths:
    - 'debian/**'
    - 'Makefile'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: lukaszkostka/debian_gcc:${{ matrix.distro }}
      env:
        VERSION: ${{ matrix.version }}
        DH_VERBOSE: 0
    strategy:
      matrix:
        version:
          - 8.3.0
          - 8.4.0
          - 9.1.0
          - 9.2.0
          - 9.3.0
          - 10.2.0
        distro:
          - stretch
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: src
          key: gcc-source-${{ matrix.version }}

      - name: Build package
        run: make deb

      - name: Move artifacts
        run: make artifacts
        if: success()

      - uses: actions/upload-artifact@v1
        with:
          name: gcc-avr-${{ matrix.distro }}
          path: artifacts
        if: success()
